version: '3'

services:
  web:
    build: './'
    container_name: php5.4-apache2-docker-compose
    depends_on:
      - db
    links:
      - db
    volumes:
      - ./app:/var/www/html/
    ports:
      - "8045:80"  
    extra_hosts:
      - "docker-compose.local:127.0.1.1"
    environment:  
      VIRTUAL_HOST: docker-compose.local
      DATABASE_URL: db:3306'
      DATABASE_NAME: ecommerce
      DATABASE_USER: ecommerce
      DATABASE_PASS: 3c0mm3rc3
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9001 remote_enable=1
    networks:
      compose:
        aliases:
          - webserver-docker-compose-php5.4
  db:
    image: mysql:5.7
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
    container_name: mysql-docker-compose
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./build/mysql-dump:/docker-entrypoint-initdb.d
    ports:
      - "3308:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ecommerce
      MYSQL_DATABASE: ecommerce
      MYSQL_PASSWORD: 3c0mm3rc3
      MYSQL_ROOT_HOST: '%'       
    networks:
      compose:
        aliases:
          - dbserver-docker-compose
  phpmyadmin:
    container_name: phpmyadmin-docker-compose
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8046:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 3c0mm3rc3  
    networks:
      compose:
        aliases:
          - phpmyadmin-dbserver-docker-compose          
networks: 
    compose:          